version: "3.9"

x-web-variables: &web-variables
  ENV: DEV
  MYSQL_DATABASE: ${SQL_NAME-dragaliauto}
  MYSQL_USER: ${SQL_USER-root}
  MYSQL_ROOT_PASSWORD: ${SQL_PASSWORD-root}
  MYSQL_HOST: ${SQL_HOST-da.sql}

services:
  da.redis:
    image: redis:6.0.5
    container_name: da.redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  da.sql:
    container_name: da.sql
    image: mariadb:10.3-focal
    environment:
      <<: *web-variables
    ports:
      - 3306:3306
    volumes:
      - sql:/var/lib/mysql

  da.django:
    extends:
      file: ./_docker/docker-django.yml
      service: da.django
    environment:
      <<: *web-variables

  da.nginx:
    extends:
      file: ./_docker/docker-nginx.yml
      service: da.nginx
    volumes:
      - ./_docker/django/nginx.dev.conf:/etc/nginx/conf.d/app.conf
    depends_on:
      - da.django
    ports:
      - 80:80
    healthcheck:
      test: ["CMD-SHELL"]
      timeout: 10h

volumes:
  sql: {}
  redis: {}