version: "3.9"

x-web-variables: &web-variables
  ENV: DEV
  MYSQL_DATABASE: ${SQL_NAME-dragaliagg}
  MYSQL_USER: ${SQL_USER-root}
  MYSQL_ROOT_PASSWORD: ${SQL_PASSWORD-root}
  MYSQL_HOST: ${SQL_HOST-dg.sql}
  DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME-admin}
  DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD-admin}
  DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL-admin@admin.com}
  DJANGO_SECRET_KEY: ${DJANGO_SUPERUSER_EMAIL-secret}
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID-1234}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY-1234}
  AWS_S3_REGION_NAME: ${AWS_S3_REGION_NAME-us-east-1}

services:
  dg.sql:
    container_name: dg.sql
    image: mariadb:10.3-focal
    environment:
      <<: *web-variables
    ports:
      - 3306:3306
    volumes:
      - sql:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_unicode_ci']

  dg.django:
    extends:
      file: ./_docker/docker-django.yml
      service: dg.django
    environment:
      <<: *web-variables

volumes:
  sql: {}