version: "3.9"

x-web-variables: &web-variables
  ENV: PROD
  MYSQL_DATABASE: ${SQL_NAME-dragaliauto}
  MYSQL_USER: ${SQL_USER-root}
  MYSQL_ROOT_PASSWORD: ${SQL_PASSWORD-root}
  MYSQL_HOST: ${SQL_HOST-dg.sql}
  DJANGO_SECRET_KEY: ${DJANGO_SUPERUSER_EMAIL-secret}

services:
  dg.django:
    extends:
      file: ./_docker/docker-django.yml
      service: dg.django
    environment:
      <<: *web-variables
    entrypoint: /entrypoint.sh

  dg.nginx:
    extends:
      file: ./_docker/docker-nginx.yml
      service: dg.nginx
    volumes:
      - ./_docker/nginx/nginx.conf:/etc/nginx/conf.d/app.conf
    depends_on:
      - dg.django
    ports:
      - 80:80
    healthcheck:
      test: ["CMD-SHELL", "wget -O /dev/null http://dg.nginx:80 || exit 1"]
      timeout: 10s
  
  autoheal:
    extends:
      file: ./_docker/docker-autoheal.yml
      service: autoheal
