- name: Provision Host
  hosts: "{{ target }}"
  remote_user: ubuntu

  tasks:
    - name: Copy Private Key
      copy:
        force: no
        src: /home/ubuntu/.ssh/id_rsa
        dest: /home/ubuntu/.ssh/id_rsa
        mode: 0600

    - name: Git Pull
      ansible.builtin.git:
        repo: git@github.com:jedi-gg/dragaliagg.git
        dest: /home/ubuntu/app
        version: main
        accept_hostkey: yes
        update: yes
        clone: yes

    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: "True"

    - name: Install packages
      become: true
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - acl
          - ansible
        state: latest

    - name: Docker - Add GPG Key
      become: true
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        keyring: /usr/share/keyrings/docker-archive-keyring.gpg
        state: present

    - name: Docker - Add Apt Repo
      become: true
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: "True"

    - name: Install packages
      become: true
      apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest

    - name: Docker Compose - Install
      become: true
      command: curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64" -o /usr/local/bin/docker-compose

    - name: Docker Compose - Set Permissions
      become: true
      command: chmod +x /usr/local/bin/docker-compose

    - name: Add ubuntu user to Docker group
      become: true
      command: usermod -aG docker ubuntu

    - name: Give log access ubuntu
      become: true
      ansible.posix.acl:
        path: /var/log/
        entry: default:user:ubuntu:rwx
        state: present

    - name: Give log access ubuntu
      become: true
      ansible.posix.acl:
        path: /var/log/
        entry: user:ubuntu:rwx
        state: present

    - name: Give log access root
      become: true
      ansible.posix.acl:
        path: /var/log/
        entry: default:user:ubuntu:rwx
        state: present

    - name: Give log access root
      become: true
      ansible.posix.acl:
        path: /var/log/
        entry: user:ubuntu:rwx
        state: present

    - name: Copy Docker daemon config
      become: true
      copy:
        force: no
        src: /home/ubuntu/docker.daemon.json
        dest: /etc/docker/daemon.json

    - name: Restart Docker
      become: True
      command: service docker restart

    - name: Reset ssh connection to allow user changes
      meta: reset_connection

    - name: Docker Compose Up
      command: docker-compose -f docker-compose.prod.web.yml up -d
      args:
        chdir: /home/ubuntu/app

    - name: Collect Static
      command: docker exec dg.django python manage.py collectstatic --noinput

    - name: Restart python
      command: docker-compose -f docker-compose.prod.web.yml restart dg.django
      args:
        chdir: /home/ubuntu/app

    - name: Copy bash_aliases file if exits
      copy:
        force: no
        remote_src: yes
        src: /home/ubuntu/app/_prod/.bash_aliases
        dest: /home/ubuntu/.bash_aliases
