version: "3.9"

services:
  dg.django:
    build:
      context: ../
      dockerfile: ./_docker/django/Dockerfile
    image: dg.django
    container_name: dg.django
    tty: true
    ports:
      - 8000:8000
    volumes:
      - ../:/srv/app
    restart: on-failure
