version: "3.9"

services:
  dg.nginx:
    image: nginx:alpine
    container_name: dg.nginx
    tty: true
    volumes:
      - ../:/srv/app
    healthcheck:
      test: ["CMD-SHELL", "wget -O /dev/null http://dg.nginx || exit 1"]
      timeout: 10s
    labels:
      - "autoheal=true"
    restart: unless-stopped
